
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://132.226.173.20:3306/const5?serverTimezone=Asia/Seoul
    username: root
    password: "!!Tess94"


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

logging.level:
  org.hibernate.SQL: debug